### ISSUE TITLE
ZoneMinder 1.32.3 Release

### ISSUE THREAD

**Issue by knight-of-ni** [fedberry/zoneminder-nginx#1]
I have updated this repo with the latest ZoneMinder 1.32.3 release.

This package has been split into sub-packages to allow compatibility with other web servers. Here is a breakdown of the available packages:

- zoneminder - Meta-package installs zoneminder-common and zoneminder-httpd. This exists soley for backwards compatibility.
- zoneminder-common - Common files that do not differ based on the web server
- zoneminder-httpd - Files needed for compatibility with the Apache web server
- zoneminder-nginx - Files needed for compatibility with the Nginx web server

@agrez would you mind changing the name of this repo to just "zoneminder"?

**Comment by agrez** [comment]
Thanks @knight-of-ni. Yep, will update the name for you and trigger builds for f28 & f29

**Comment by knight-of-ni** [comment]
I just installed the 1.32.3 package currently in FedBerry testing, and it works greats. Thanks!
